#ifndef CONFIG_INONIO_H
#define CONFIG_INONIO_H

#include "../../config.h"

#undef MOUSEKEY_MOVE_MAX
#define MOUSEKEY_MOVE_MAX       127
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 20
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 15
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 4
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 80
#undef MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA     5

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 200
#undef MOUSEKEY_WHEEL_MAX
#define MOUSEKEY_WHEEL_MAX      3
#undef MOUSEKEY_WHEEL_DELTA
#define MOUSEKEY_WHEEL_DELTA    1
#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 80

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 1000

#undef TAPPING_TERM
#define TAPPING_TERM 180

#undef  RGBLIGHT_HUE_STEP
#define RGBLIGHT_HUE_STEP 24

#undef  RGBLIGHT_SAT_STEP
#define RGBLIGHT_SAT_STEP 24

#undef  RGBLIGHT_VAL_STEP
#define RGBLIGHT_VAL_STEP 24

#undef  RGBLIGHT_BRI_STEP
#define RGBLIGHT_BRI_STEP 24

#undef  RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_LIMIT_VAL 255

#define RGBLIGHT_SLEEP

#undef IGNORE_MOD_TAP_INTERRUPT
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#ifdef DEBUG_ENABLE
#undef NO_PRINT
#undef NO_DEBUG
#endif

#endif
