# avrdude -p atmega32u4 -c avr109 -P /dev/tty.usbmodem1411  -U flash:w:../../.build/lets_split_rev2_inon.hex

CONSOLE_ENABLE = yes
RGBLIGHT_ENABLE = yes
MOUSEKEY_ENABLE = yes

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
