# avrdude -p atmega32u4 -c avr109 -P /dev/tty.usbmodem1411  -U flash:w:../../.build/lets_split_rev2_inon.hex

# max file size: 28672

USE_I2C = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
DEBUG_ENABLE = no

CONSOLE_ENABLE = yes
RGBLIGHT_ENABLE = yes
MOUSEKEY_ENABLE = yes

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
