#ifndef CONFIG_INONIO_H
#define CONFIG_INONIO_H

#include "../../config.h"

#undef MOUSEKEY_MOVE_MAX
#define MOUSEKEY_MOVE_MAX       127
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 50
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 20
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 3
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 10

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 3
#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 1000
#undef MOUSEKEY_WHEEL_MAX
#define MOUSEKEY_WHEEL_MAX      110
#undef MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA     5
#undef MOUSEKEY_WHEEL_DELTA
#define MOUSEKEY_WHEEL_DELTA    1

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 1000

#undef TAPPING_TERM
#define TAPPING_TERM 200

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#ifdef DEBUG_ENABLE
#undef NO_PRINT
#undef NO_DEBUG
#endif

#endif
